### ISSUE TITLE
I have a question about Data-Driven Design for Fourier Ptychographic Microscopy

### ISSUE THREAD

**Issue by TissueNam** [kellman/LearnedDesignFPM#1]
Hello. Mr. Kellman
I am a student studying Fourier Ptychographic microscopy.
I was watching a Learned Design FPM you wrote on github.
It really helps me a lot. thank you.
But there is a problem.

https://github.com/kellman/LearnedDesignFPM
Among these, in Demonstration

1.Download all of the training and experimental data from "here".
We provide synthetic training and experimental testing data for both amplitude and quantitative phase imaging applications.

When I press "here", I get an error of "404 Not Found".

Could you restore the link? Or could I get the training and experimental data?
I'm begging you. And Happy New Year! Mr. Kellman!

**Comment by kellman** [comment]
https://drive.google.com/a/berkeley.edu/file/d/1U41k1hFSJ3FS6rh6etAAdX9AkTCUXRsK/view?usp=sharing
https://drive.google.com/a/berkeley.edu/file/d/1kM_ub7yTCrh68ADykjiCUHCXAI6ou7w4/view?usp=sharing
https://drive.google.com/a/berkeley.edu/file/d/1oQ-K53pDB4ilDVFOLxTe8r3xjR3NBViM/view?usp=sharing
https://drive.google.com/a/berkeley.edu/file/d/1vfvI_AqS5XGdLabum4dB0jOl2u0AAFVy/view?usp=sharing

**Comment by Smallmachines-Gin** [comment]
Hello, Kellman.
I am also a student studying FPM.

I have question about metadata.mat file. It shoots No such file error.

I got stuck in multiplexed FPM optimization when I choose LED pattern and brightness.
So, it was really helpful your papers.
I was trying to execute your opensource about PbNN paper.

My developing environment is below,
- intel cpu
- titan v gpu
- cuda ver 11.0
- anaconda, python

I think I downloaded all of the files required, but got some errors.
The first error was about Cuda version and Path of the training mat file.

I executed with this command below.

python train.py --verbose True --training_iter 3 --batch_size 5 --test_freq 1 --step_size 0.01 --num_unrolls 75 --alpha 0.1 --num_bf 1 --num_df 9 --loss abs --tensorboard True --path=./DATA

DATA dir has 4 .mat files (experimental_amplitude_USAF_data, experimental_phase_USAF_data, training_data_amplitude, training_data_phase)

Please answer about metadata.mat, should I make that myself or not?

Thanks, happy new year!

**Comment by itdar** [comment]
Hello, Kellman.
I am also a student studying FPM.

I have question about metadata.mat file. It shoots No such file error.

I got stuck in multiplexed FPM optimization when I choose LED pattern and brightness.
So, it was really helpful your papers.
I was trying to execute your opensource about PbNN paper.

My developing environment is below,

intel cpu
titan v gpu
cuda ver 11.0
anaconda, python
I think I downloaded all of the files I can, but got some errors.
The first error was about Cuda version and Path of the training mat file.

I executed with this command below.

python train.py --verbose True --training_iter 3 --batch_size 5 --test_freq 1 --step_size 0.01 --num_unrolls 75 --alpha 0.1 --num_bf 1 --num_df 9 --loss abs --tensorboard True --path=./DATA

DATA dir has 4 .mat files (experimental_amplitude_USAF_data, experimental_phase_USAF_data, training_data_amplitude, training_data_phase)

Please answer about metadata.mat,
should I make that myself using generate_training_dataset.py with files above?

Thanks, happy new year!
